services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./app/database/DDL.sql:/docker-entrypoint-initdb.d/10-schema.sql:ro
    command: ["--default-authentication-plugin=mysql_native_password"]

  adminer:
    image: adminer
    depends_on: [db]
    ports: ["8080:8080"]

  web:
    build: .
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://app:app@db:3306/challenge
      ALERT_THRESH_TEMPERATURA: "80"
      ALERT_THRESH_VIBRACAO: "80"
      ALERT_MIN_STREAK: "1"
      ALERT_WINDOW_SECONDS: "120"
      MODEL_DIR: /app/app/ml
    volumes:
      - ./:/app
    depends_on: [db]
    ports: ["5001:5000"]
    command: sh -lc "python -m app.seed && flask --app app/wsgi.py run --host=0.0.0.0 --port=5000"

  simulator:
    build: .                   # usa a mesma imagem do "web" (Python + deps)
    depends_on: [web]
    environment:
      API_URL: http://web:5000/api/readings
      INTERVAL_SEC: "2"
      SENSORS: "1,2,3,4,5,6"
      CYCLE_SECONDS: "120"
      ALERT_THRESH: "80"
      ALERT_MIN_STREAK: "3"
    volumes:
      - ./:/app
    working_dir: /app
    command: python -u -m app.simulador.sensor_sim
    restart: unless-stopped

volumes:
  dbdata:
